database:
  driver: mysql
  host: localhost
  user: root
  name: roomcafe
  port: 3306
  default: true
app:
  mode: debug
  host: room.cafe
  port: 8080
  secure: false
  secret: secret
qiniu:
  access_key: access_key
  secret_key: secret_key
  rtn_appid:
  rtn_addr: https://rtc.qiniuapi.com
herewhite:
  mini_token:
  host: https://cloudcapiv3.herewhite.com
oauth:
  google:
    client_id:
    client_secret:
    auth_url:
    token_url:
    scopes: []
  github:
    client_id:
    client_secret:
    auth_url:
    token_url:

